name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0' # Or whatever .NET version you are using

      - name: Publish Blazor app
        run: dotnet publish -c Release -o release --nologo

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
          CLEAN: true
