name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # changed to main (not master)

permissions:
  contents: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
      
      # Setup .NET 9 SDK (Preview)
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          include-prerelease: true

      # Publish Blazor project
      - name: Publish Blazor project
        run: dotnet publish Bude-Tools-Blazor.csproj -c Release -o release --nologo

      # Update base href dynamically based on repo name
      - name: Update base href
        run: sed -i 's/<base href="\/" \/>/<base href="\/bude-tools-blazor\/" \/>/g' release/wwwroot/index.html

      # Copy index.html to 404.html for SPA routing
      - name: Create 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      # Add .nojekyll file to allow Blazor files starting with "_"
      - name: Add .nojekyll
        run: touch release/wwwroot/.nojekyll

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: release/wwwroot
          clean: true
